<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Prédictions Sportives Gratuites</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
    <style>
        .prediction-card {
            background: #f8f9fa;
            border-radius: 15px;
            transition: transform 0.2s;
        }
        .prediction-card:hover {
            transform: translateY(-5px);
        }
    </style>
</head>
<body class="bg-light">
    <div class="container py-5">
        <h1 class="text-center mb-4"><i class="fas fa-futbol"></i> Prédictions Sportives</h1>
        
        <!-- Section Football -->
        <div class="row mb-4">
            <div class="col-md-8 mx-auto">
                <div class="card prediction-card p-3 mb-3">
                    <h3><i class="fas fa-soccer-ball"></i> Prochain Match de Football</h3>
                    <div id="football-match" class="mb-3"></div>
                    <button class="btn btn-primary" onclick="generateFootballPrediction()">
                        Générer une Prédiction
                    </button>
                    <div id="football-result" class="mt-3 fw-bold"></div>
                </div>
            </div>
        </div>

        <!-- Section Basketball -->
        <div class="row">
            <div class="col-md-8 mx-auto">
                <div class="card prediction-card p-3">
                    <h3><i class="fas fa-basketball-ball"></i> Prochain Match de Basketball</h3>
                    <div id="basketball-match" class="mb-3"></div>
                    <button class="btn btn-danger" onclick="generateBasketballPrediction()">
                        Générer une Prédiction
                    </button>
                    <div id="basketball-result" class="mt-3 fw-bold"></div>
                </div>
            </div>
        </div>
    </div>

    <script>
        // Données mockées (à remplacer par une API réelle)
        const matches = {
            football: {
                team1: "PSG",
                team2: "OM",
                date: "20 novembre 2023"
            },
            basketball: {
                team1: "ASVEL",
                team2: "Monaco",
                date: "21 novembre 2023"
            }
        };

        // Afficher les matchs initiaux
        document.getElementById('football-match').innerHTML = `
            ${matches.football.team1} vs ${matches.football.team2}<br>
            <small>${matches.football.date}</small>
        `;

        document.getElementById('basketball-match').innerHTML = `
            ${matches.basketball.team1} vs ${matches.basketball.team2}<br>
            <small>${matches.basketball.date}</small>
        `;

        // Logique de prédiction aléatoire (basique)
        function generateFootballPrediction() {
            const outcomes = ["Victoire", "Nul", "Défaite"];
            const probabilities = ["60%", "25%", "15%"];
            const result = `${matches.football.team1} : ${outcomes[0]} (${probabilities[0]})`;
            document.getElementById('football-result').innerHTML = result;
        }

        function generateBasketballPrediction() {
            const pointsDiff = Math.floor(Math.random() * 15) + 1;
            const result = `Victoire de ${matches.basketball.team1} par ${pointsDiff} points`;
            document.getElementById('basketball-result').innerHTML = result;
        }
    </script>
</body>
</html>
